version: "3.9"

services: 
  database:
    image: postgres
    container_name: database_fluency
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=fluency
      - POSTGRES_DB=fluency-code
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: fluency-code
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    

volumes:
  pgdata:
    driver: local
  